# forked from https://github.dev/jim60105/docker-twitch-recorder

services:
  twitch-stream-recorder:
    image: ghcr.io/civon/twitch-stream-recorder
    restart: always
    env_file:
      - .env
    volumes:
      - ${archive}:/app/rec
